{% set name = "ibis-bigquery" %}
{% set version = "2.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ibis-bigquery-{{ version }}.tar.gz
  sha256: 1d94c64b8803b07f7dce41027238c727e9f38ccbcc951496f62aeb0898e2a3e4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - ibis-framework-core >=2.0.0,<4.0.0dev
    - db-dtypes >=0.3.0,<2.0.0dev
    - google-cloud-bigquery >=1.12.0,<4.0.0dev
    - google-cloud-bigquery-storage >=1.0.0,<3.0.0dev
    - packaging >=17.0
    - pyarrow >=1.0.0,<10.0.0dev
    - pydata-google-auth
    - python >={{ python_min }}
    - sqlalchemy >=1.4,<2.0
    # Fixes for transitive deps from Ibis
    - atpublic <3,>=2.3
    - regex <2022.0.0,>=2021.7.6

test:
  imports:
    - ibis_bigquery
    - ibis_bigquery.udf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ibis-project/ibis-bigquery
  summary: Ibis BigQuery backend
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
